include themes/mocha.conf

#font_family      MesloLGMDZ Nerd Font
font_family      JetBrains Mono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 10

cursor_shape block
shell_integration no-cursor

mouse_hide_wait 3.0

enable_audio_bell no

hide_window_decorations yes

tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         angled
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Mappings
map kitty_mod+t new_tab_with_cwd
