#! /usr/bin/bash
 
no_quotes() {
    echo $(echo -n $1 | sed "s/'//g")
}

get_battery_info() {
    echo $(
        upower -i $(upower -e | grep BAT) \
        | grep $1 \
        | awk '{ print $2 }'
    )
}

toggle_nag() {
    pkill -f -TERM  "$(no_quotes "$1")" && exit 0

    for cmd in "${@:2}"; do
        pkill -f -TERM "$(no_quotes "$cmd")"
    done

    eval "$1"
}

# -----------------------------------------------------------------------------
# Main sub commands
# -----------------------------------------------------------------------------

shoot() {
    if [[ $2 == 'select' ]]; then
        local dimensions="$(slurp)"
        [[ -z $dimensions ]] && exit 0
        grim -g "$dimensions" $1
    else
        grim $1
    fi 

    action=$(
        notify-send "Screenshot" "Saved as $1" \
            -u normal -a 'grim' -t 5000 -w \
            -A "default=$1"
    )

    [[ $action == 'default' ]] && xdg-open $1
} 

appmenu() {
    pkill wofi && exit 0
    wofi -i -I -l 7 -w 25% -p 'App name...' --show=drun
}

powergov() {
    local gov=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
    local percent=$(get_battery_info 'percentage' | awk '{ print int($1) }')
    local charging=$(get_battery_info 'state')
    local class=''

    if [[ $charging == 'charging' ]] && (( percent < 100 )); then
        class='charging'
    elif (( percent <= $1 )) && (( percent > $2 )); then
        class='warning'
    elif (( percent <= $2 )); then
        class='critical'
    fi

    case $gov in
        'powersave')
            echo -e "󰌪\n${gov^}\n${class}"
        ;;
        'performance')
            echo -e "\n${gov^}"
        ;;
        *)
            echo -e "$gov\n\n${class}"
        ;;
    esac
}

powerctl() {
    local shutdown_cmd="swaynag -t powerctl -m 'Shutdown now' -B 'Yes' 'shutdown now'"
    local reboot_cmd="swaynag -t powerctl -m 'Reboot now' -B 'Yes' 'reboot'"
    local session_exit_cmd="swaynag -t powerctl -m 'Exit Wayland session' -B 'Yes' 'swaymsg exit'"

    case $1 in
        'shutdown')
            toggle_nag "$shutdown_cmd" "$reboot_cmd" "$session_exit_cmd"
        ;;
        'reboot')
            toggle_nag "$reboot_cmd" "$shutdown_cmd" "$session_exit_cmd"
        ;;
        'session-exit')
            toggle_nag "$session_exit_cmd" "$shutdown_cmd" "$reboot_cmd"
        ;;
        'lock')
            lock
        ;;
    esac
}

sleep 0.1

subcmds="shoot appmenu powergov powerctl"

for cmd in $subcmds; do
    [[ $1 == $cmd ]] && eval "$cmd ${@:2}" && exit 
done

echo "there is no subcommand $1"
exit 1
