#! /usr/bin/bash
 
no_quotes() {
    echo $(echo -n $1 | sed "s/'//g")
}

# -----------------------------------------------------------------------------
# Main sub commands
# -----------------------------------------------------------------------------

lock() {
    playerctl pause 2> /dev/null
    swaylock -f
}

shoot() {
    if [[ $2 == 'select' ]]; then
        local dimensions="$(slurp)"
        [[ -z $dimensions ]] &&  exit 0
        grim -g $dimensions $1
    else
        grim $1
    fi 
} 

appmenu() {
    pkill wofi && exit 0
    wofi -i -I -l 7 -w 25% -p 'App name...' --show=drun
}

powergov() {
    local gov=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
    local percent=$(
        upower -i /org/freedesktop/UPower/devices/battery_BAT1 \
        | grep percentage \
        | awk '{ printf int($2) }'
    )
    local class=''

    if (( percent <= $1 )) && (( percent > $2 )); then
        class='warning'
    elif (( percent <= $2 )); then
        class='critical'
    fi

    case $gov in
        'powersave')
            echo -e "󰌪\n${gov^}\n${class}"
        ;;
        'performance')
            echo -e "\n${gov^}\n${class}"
        ;;
        *)
            echo -e "$gov\n\n${class}"
        ;;
    esac
}

powerctl() {
    local shutdown_cmd="swaynag -t powerctl -m 'Shutdown now' -B 'Yes' 'shutdown now'"
    local reboot_cmd="swaynag -t powerctl -m 'Reboot now' -B 'Yes' 'reboot'"
    local session_exit_cmd="swaynag -t powerctl -m 'Exit Wayland session' -B 'Yes' 'swaymsg exit'"

    toggle_nag() {
        pkill -f -TERM  "$(no_quotes "$1")" && exit 0

        for cmd in "${@:2}"; do
            pkill -f -TERM "$(no_quotes "$cmd")"
        done

        eval "$1"
    }

    case $1 in
        'shutdown')
            toggle_nag "$shutdown_cmd" "$reboot_cmd" "$session_exit_cmd"
        ;;
        'reboot')
            toggle_nag "$reboot_cmd" "$shutdown_cmd" "$session_exit_cmd"
        ;;
        'session-exit')
            toggle_nag "$session_exit_cmd" "$shutdown_cmd" "$reboot_cmd"
        ;;
        'lock')
            lock
        ;;
    esac
}

sleep 0.1

case $1 in
    'lock')
        lock
    ;;
    'shoot')
        shoot $@
    ;;
    'appmenu')
        appmenu $@
    ;;
    'powergov')
        powergov $@
    ;;
    'powerctl')
        powerctl $@
    ;;
    *)
        exit 1
esac
