#! /usr/bin/bash
 
KRIPT_INSTALL_TARGET="$HOME/.local/bin"
DOTCONFIG_INSTALL_TARGET="$HOME/.config"
COLORS_INSTALL_TARGETS='./dotconfig/sway/colors ./dotconfig/wofi/colors ./dotconfig/waybar/colors'

ensure_target() {
    [[ ! -d $1 ]] && mkdir -p $1
}
 
install() {
    ensure_target $KRIPT_INSTALL_TARGET
    ln -srf 'kript' "$KRIPT_INSTALL_TARGET/kript"
    echo "Symlinked kript as $KRIPT_INSTALL_TARGET/kript"
    stow -v 'dotconfig' -t $DOTCONFIG_INSTALL_TARGET  
}

refresh() {
    ensure_target $KRIPT_INSTALL_TARGET
    ln -srf 'kript' "$KRIPT_INSTALL_TARGET/kript"
    echo "Symlinked kript as $KRIPT_INSTALL_TARGET/kript"
    stow -vR 'dotconfig' -t $DOTCONFIG_INSTALL_TARGET  
}

uninstall() {
   rm "$KRIPT_INSTALL_TARGET/kript" 
   echo "Removed symlink $KRIPT_INSTALL_TARGET/kript"
   stow -vD 'dotconfig' -t $DOTCONFIG_INSTALL_TARGET
}

refresh_colors() {
    for t in $COLORS_INSTALL_TARGETS; do
        stow -vR 'colors' -t $t
    done    
}

subcmds='install refresh uninstall refresh_colors'

for cmd in $subcmds; do
    [[ $1 == $cmd ]] && eval "$cmd" && exit
done

echo "$1 is not a subcommand"
exit 1
