theme = "gruvbox_dark_soft"

[editor]
scrolloff = 8
line-number = "relative"
true-color = true
auto-completion = false
color-modes = true
end-of-line-diagnostics = "hint"
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal."@"]
m = ":pipe sed 's/[ \t]*$//g'"
