#! /usr/bin/bash

gov=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)

case $gov in
    'powersave')
        echo -e "󰌪\n${gov^}\n${gov}"
    ;;
    'performance')
        echo -e "\n${gov^}\n${gov}"
    ;;
    *)
        echo -e "$gov\n\n${gov}"
    ;;
esac
