#! /usr/bin/bash

volume=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)
alsa_id=$(
    wpctl inspect @DEFAULT_AUDIO_SOURCE@ \
        | grep 'alsa.id' \
        | awk -F ' = ' '{print substr($NF, 2, length($NF) - 2)}'
)

if [[ -z $(echo $volume | awk '{print $3}') ]]; then
    magnitude=$(echo $volume | awk '{print $2 * 100}')
    echo -e "$magnitude% 󰍬\n$alsa_id"
else
    echo -e "󰍭\n$alsa_id\nmuted"
fi
