#! /usr/bin/bash

if [[ $1 == 'now' ]]; then
    playerctl pause
    swaylock -f
elif [[ -z $1 ]]; then
    swayidle -w \
        timeout 300 'playerctl pause && swaylock -f' \
        timeout 600 'swaymsg "output * power off"' \
            resume 'swaymsg "output * power on"' \
        before-sleep 'swaylock -f'
fi
