#! /usr/bin/bash

sleep 0.1  # say no to fast clicks

shutdown_cmd="swaynag -t powerctl -m 'Shutdown now' -B 'Yes' 'shutdown now'"
reboot_cmd="swaynag -t powerctl -m 'Reboot now' -B 'Yes' 'reboot'"
session_exit_cmd="swaynag -t powerctl -m 'Exit Wayland session' -B 'Yes' 'swaymsg exit'"

no_quotes() {
    echo $(echo -n $1 | sed "s/'//g")
}

toggle_nag() {
    local cmd_cleaned=$(no_quotes "$1")
    local proc=$(pgrep -f "$cmd_cleaned")

    (( $proc )) && kill $proc && exit 0

    for cmd in "${@:2}"; do
        cmd_cleaned=$(no_quotes "$cmd")
        proc=$(pgrep -f "$cmd_cleaned")
        (( $proc )) && kill $proc
    done

    eval "$1"
}

case $1 in
    'shutdown')
        toggle_nag "$shutdown_cmd" "$reboot_cmd" "$session_exit_cmd"
    ;;
    'reboot')
        toggle_nag "$reboot_cmd" "$shutdown_cmd" "$session_exit_cmd"
    ;;
    'session-exit')
        toggle_nag "$session_exit_cmd" "$shutdown_cmd" "$reboot_cmd"
    ;;
    'lock')
        ~/.config/scripts/lockit
    ;;
esac
