#! /usr/bin/bash

case $1 in
    'shutdown')
        swaynag -t powerctl -m 'Shutdown now?' -B 'Yes' 'shutdown now'
    ;;
    'reboot')
        swaynag -t powerctl -m 'Reboot now?' -B 'Yes' 'reboot'
    ;;
    'session-exit')
        swaynag -t powerctl -m 'Exit Wayland session?' -B 'Yes' 'swaymsg exit'
    ;;
    'lock')
        ~/.config/scripts/lockit now
    ;;
esac
