#! /usr/bin/bash

gov=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
percent=$(
    upower -i /org/freedesktop/UPower/devices/battery_BAT1 \
    | grep percentage \
    | awk '{ printf int($2) }'
)
class=''

if (( percent <= $1 )) && (( percent > $2 )); then
    class='warning'
elif (( percent <= $2 )); then
    class='critical'
fi

case $gov in
    'powersave')
        echo -e "󰌪\n${gov^}\n${class}"
    ;;
    'performance')
        echo -e "\n${gov^}\n${class}"
    ;;
    *)
        echo -e "$gov\n\n${class}"
    ;;
esac
