[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "html"
auto-format = false

[[language]]
name = "python"
language-servers = ["pylsp"]
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"
