#!/usr/bin/bash

# ref: https://stackoverflow.com/a/1371283
result=${PWD%%+(/)}  # trim however many trailing slashes exist
result=${result##*/} # remove everything before the last / that still remains
result=${result:-/}  # correct for dirname=/ case

tmux new-session -s $result nvim\;\
    neww\;\
    selectw -t 0\;
